name: Override environment variable
on: push
env:
  EXAMPLE: Defined by workflow level
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: echo "${EXAMPLE}"
      - env:
          ESAMPLE: Defined by step level
        run: echo "${EXAMPLE}"
